server:
  port: 80
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/unimaster
    username: developer
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true